name: CI

on:
  push:

jobs:
  build:
    name: Build (Static)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Haskell
      uses: haskell/actions/setup@v1
      with:
        ghc-version: "8.10.4"

    - name: Install Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Project
      run: |
        docker run -tv $PWD:/mnt utdemir/ghc-musl:v20-ghc8104 \
        /bin/bash -c 'cd /mnt && cabal update && cabal install --enable-executable-static --installdir=build && ldd build/Fungoid'
